name: Upload Test
on:
  workflow_dispatch:
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: test upload
    steps:
      - name: upload
        id: upload 
        with:
          server: playground.direktiv.io
          namespace: trent
          variable: test3
          data: ./helloworld
          token: ${{ secrets.DIREKTIV_TOKEN }}
        uses: vorteil/direktiv-actions-ghupload@test
      - name: get output
        run: |
          echo ${{ steps.execute.outputs.body }}