name: Upload json data to workflow
on:
  workflow_dispatch:
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: test upload
    steps:
      - name: upload
        id: upload 
        with:
          server: playground.direktiv.io
          namespace: trent
          variable: test2
          workflow: test
          data: |
            {
              "hello": "world"
            }
          token: ${{ secrets.DIREKTIV_TOKEN }}
        uses: vorteil/direktiv-actions-ghupload@master
      - name: get output
        run: |
          echo ${{ steps.execute.outputs.body }}